DROP TABLE IF EXISTS PRICES;
DROP TABLE IF EXISTS PRODUCTS;
DROP TABLE IF EXISTS BRANDS;

CREATE TABLE BRANDS (
BRAND_ID INTEGER NOT NULL,
NAME VARCHAR (50) NOT NULL,
PRIMARY KEY (BRAND_ID)
);

CREATE TABLE PRODUCTS (
PRODUCT_ID INTEGER NOT NULL,
NAME VARCHAR (50) NOT NULL,
PRIMARY KEY (PRODUCT_ID)
);

CREATE TABLE PRICES (
PRICE_LIST INTEGER NOT NULL,
PRODUCT_ID INTEGER NOT NULL,
BRAND_ID INTEGER NOT NULL,
START_DATE TIMESTAMP NOT NULL,
END_DATE TIMESTAMP NOT NULL,
priority INTEGER NOT NULL,
price DOUBLE NOT NULL,
curr VARCHAR (3) NOT NULL,
PRIMARY KEY (PRICE_LIST),
FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID) ON DELETE CASCADE,
FOREIGN KEY (BRAND_ID) REFERENCES BRANDS(BRAND_ID) ON DELETE CASCADE
);